### ISSUE TITLE
Not generating the object file "crash_handler.o"

### ISSUE THREAD

**Issue by lieal42** [CasualPokePlayer/flowtimer.gbc#2]
OS: macOS Monterey 12.5.1
Processor: 2,6 GHz 6-Core Intel Core i7
rgbasm version: 0.5.2
(other object files were generated in obj directory)

**Comment by CasualPokePlayer** [comment]
Python 3 is required for building.

**Comment by lieal42** [comment]
ok, I had to add "python3" after "PY :=" in the Makefile(l.22) and execute the make command twice; but it worked
